quarkus.oidc.auth-server-url=${keycloak.url}/realms/quarkus/
quarkus.oidc.client-id=quarkus-app
quarkus.oidc.credentials.secret=secret
quarkus.casdoor.endpoint=${keycloak.url}
quarkus.keycloak.devservices.enabled=false
